### ENDPONTS USER

POST http://localhost:3003/user/signup
Content-Type: application/json

{
   "name": "Leandro Lima",   
   "email": "leandro@email.com",
   "password": "labook16"
}

###

### ENDPONTS POST


POST http://localhost:3003/post/post
Content-Type: application/json

{
   "author_id": "5b4ae49b-c110-4ec8-843a-4016940c133f",
   "description": "Olá rede! Olhem esta beleza de foto do meu fds na praia de Cabo Branco, em João Pessoa - PB",
   "photo": "Foto_praia.png",
   "type": "Normal"
}
###

GET http://localhost:3003/post/:id
Content-Type: application/json

{
   "id": "180e392a-bed1-4b48-9e54-2f57227235f9"

}

